import path from "node:path";
import { templateDefinitions } from "../config/defaults.js";
import type {
  GenerateReadmeResult,
  RepoAnalysis,
  SectionId
} from "../types/index.js";
import { generateBadges } from "./generate-badges.js";
import { generateInstallation } from "./generate-installation.js";
import {
  generateCliUsage,
  generateQuickStart,
  generateUsage
} from "./generate-usage.js";
import { generateStructure } from "./generate-structure.js";
import {
  bulletList,
  formatMarkdown,
  table,
  wrapManagedSection
} from "../utils/markdown.js";
import { runScriptCommand } from "../utils/commands.js";

const SECTION_TITLES: Record<SectionId, string> = {
  badges: "Badges",
  overview: "Overview",
  why: "Why This Project Exists",
  features: "Features",
  "tech-stack": "Tech Stack",
  installation: "Installation",
  "quick-start": "Quick Start",
  usage: "Usage",
  "cli-usage": "CLI Usage",
  scripts: "Available Scripts",
  environment: "Environment Variables",
  structure: "Project Structure",
  development: "Development Workflow",
  "ci-cd": "CI/CD Notes",
  contributing: "Contributing",
  security: "Security",
  license: "License"
};

export async function generateReadme(
  analysis: RepoAnalysis
): Promise<GenerateReadmeResult> {
  const template = templateDefinitions[analysis.config.template];
  const sections: string[] = [];
  const includedSections: SectionId[] = [];

  for (const sectionId of analysis.config.sectionOrder.length > 0
    ? analysis.config.sectionOrder
    : template.sectionOrder) {
    if (!analysis.config.sections[sectionId]) {
      continue;
    }

    const body = buildSection(sectionId, analysis).trim();

    if (body.length === 0) {
      continue;
    }

    includedSections.push(sectionId);
    sections.push(
      wrapManagedSection(sectionId, SECTION_TITLES[sectionId], body)
    );
  }

  const content = await formatMarkdown(
    [
      `# ${analysis.config.title ?? analysis.metadata.title}`,
      "",
      "> Generated by readmefy from checked-in repository metadata. Re-run the CLI to keep this document current.",
      "",
      sections.join("\n\n")
    ].join("\n")
  );

  return {
    content,
    sections: includedSections,
    template: analysis.config.template
  };
}

function buildSection(sectionId: SectionId, analysis: RepoAnalysis): string {
  switch (sectionId) {
    case "badges":
      return generateBadges(analysis).join(" ");
    case "overview":
      return buildOverview(analysis);
    case "why":
      return analysis.config.why ?? "";
    case "features":
      return buildFeatures(analysis);
    case "tech-stack":
      return buildTechStack(analysis);
    case "installation":
      return generateInstallation(analysis);
    case "quick-start":
      return generateQuickStart(analysis);
    case "usage":
      return generateUsage(analysis);
    case "cli-usage":
      return generateCliUsage(analysis);
    case "scripts":
      return buildScripts(analysis);
    case "environment":
      return buildEnvironment(analysis);
    case "structure":
      return generateStructure(analysis.structure);
    case "development":
      return buildDevelopment(analysis);
    case "ci-cd":
      return buildCi(analysis);
    case "contributing":
      return buildContributing(analysis);
    case "security":
      return buildSecurity(analysis);
    case "license":
      return buildLicense(analysis);
    default:
      return "";
  }
}

function buildOverview(analysis: RepoAnalysis): string {
  const base =
    analysis.config.customIntro ??
    analysis.metadata.description ??
    `${analysis.metadata.title} is a ${describeProject(analysis)}.`;
  const summary =
    analysis.frameworks.length > 0
      ? `Detected stack: ${analysis.frameworks.join(", ")}.`
      : "";
  return [base, summary].filter((value) => value.length > 0).join("\n\n");
}

function buildFeatures(analysis: RepoAnalysis): string {
  const configured = analysis.config.features;

  if (configured.length > 0) {
    return bulletList(configured);
  }

  const features = new Set<string>();

  features.add(describeProject(analysis));

  if (analysis.frameworks.length > 0) {
    features.add(
      `Framework and runtime signals detected from ${analysis.frameworks.join(", ")}.`
    );
  }

  if (analysis.cli.binName) {
    features.add(`CLI entrypoint exposed as \`${analysis.cli.binName}\`.`);
  }

  if (analysis.env.length > 0) {
    features.add(
      `Environment contract documented from \`.env.example\` (${analysis.env.length} variables).`
    );
  }

  if (analysis.flags.hasDocker || analysis.flags.hasCompose) {
    features.add("Docker-based workflows are checked into the repository.");
  }

  if (analysis.ci.workflows.length > 0) {
    features.add(
      `GitHub Actions automation detected in ${analysis.ci.workflows.length} workflow file(s).`
    );
  }

  if (analysis.project.primary === "monorepo") {
    features.add(
      "Workspace-oriented structure suitable for templates, packages, or apps."
    );
  }

  return bulletList([...features].slice(0, 6));
}

function buildTechStack(analysis: RepoAnalysis): string {
  const rows = [
    ["Primary type", analysis.project.primary],
    ["Template", analysis.project.template],
    ["Package manager", analysis.packageManager],
    [
      "Frameworks",
      analysis.frameworks.length > 0
        ? analysis.frameworks.join(", ")
        : "Not detected"
    ],
    ["License", analysis.license.spdx]
  ];

  return table(["Item", "Value"], rows);
}

function buildScripts(analysis: RepoAnalysis): string {
  if (analysis.scripts.length === 0) {
    return "";
  }

  const rows = analysis.scripts.map((script) => [
    script.name,
    `\`${script.command}\``,
    script.source
  ]);
  return table(["Script", "Command", "Source"], rows);
}

function buildEnvironment(analysis: RepoAnalysis): string {
  if (analysis.env.length === 0) {
    return "";
  }

  const rows = analysis.env.map((variable) => [
    `\`${variable.name}\``,
    variable.sample.length > 0 ? `\`${variable.sample}\`` : "`<required>`",
    variable.description.length > 0
      ? variable.description
      : "Documented in .env.example"
  ]);

  return table(["Variable", "Sample", "Notes"], rows);
}

function buildDevelopment(analysis: RepoAnalysis): string {
  const recommendedScripts = [
    "lint",
    "typecheck",
    "test",
    "build",
    "dev"
  ].filter((scriptName) =>
    analysis.scripts.some((script) => script.name === scriptName)
  );

  if (recommendedScripts.length > 0) {
    return codeBlockFromCommands(
      recommendedScripts.map((scriptName) =>
        runScriptCommand(analysis.packageManager, scriptName)
      )
    );
  }

  if (analysis.flags.hasMakefile) {
    return codeBlockFromCommands(["make test", "make build"]);
  }

  return codeBlockFromCommands(["git status"]);
}

function buildCi(analysis: RepoAnalysis): string {
  if (analysis.ci.workflows.length === 0) {
    return "";
  }

  const items = analysis.ci.workflows.map((workflow) => {
    const events =
      workflow.events.length > 0 ? ` (${workflow.events.join(", ")})` : "";
    return `\`${workflow.name}\` from \`${workflow.file}\`${events}`;
  });
  return bulletList(items);
}

function buildContributing(analysis: RepoAnalysis): string {
  if (!analysis.detectedFiles.includes("CONTRIBUTING.md")) {
    return "Open an issue or pull request with a focused change and the reasoning behind it.";
  }

  return "See [CONTRIBUTING.md](./CONTRIBUTING.md) for development setup, coding standards, and review expectations.";
}

function buildSecurity(analysis: RepoAnalysis): string {
  if (!analysis.detectedFiles.includes("SECURITY.md")) {
    return "Report security issues privately through your standard maintainer channel before opening a public issue.";
  }

  return "See [SECURITY.md](./SECURITY.md) for supported versions and private disclosure instructions.";
}

function buildLicense(analysis: RepoAnalysis): string {
  const fileSuffix = analysis.license.file
    ? ` in \`${path.basename(analysis.license.file)}\``
    : "";
  return `Released under the ${analysis.license.spdx} license${fileSuffix}.`;
}

function describeProject(analysis: RepoAnalysis): string {
  switch (analysis.project.primary) {
    case "next-app":
      return "Next.js application documentation infrastructure.";
    case "vite-app":
      return "Vite-based application or frontend package.";
    case "cli-tool":
      return "Installable command-line tool with repository-driven documentation.";
    case "monorepo":
      return "Multi-package workspace with shared documentation needs.";
    case "python-package":
      return "Python package analyzed from checked-in project metadata.";
    case "rust-crate":
      return "Rust crate with deterministic documentation derived from source files.";
    case "go-module":
      return "Go module with repository-derived usage and setup guidance.";
    case "dockerized-service":
      return "Dockerized service with README content generated from deployable assets.";
    case "node-library":
      return "Reusable Node.js library with deterministic README maintenance.";
    case "node-app":
    default:
      return "Repository documentation generated from the real application layout.";
  }
}

function codeBlockFromCommands(commands: string[]): string {
  return ["```bash", commands.join("\n"), "```"].join("\n");
}
